# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CidrEncoder < Formula
  desc "CLI for time efficiently encoding cidr blocks to find if an IP exists in a range"
  homepage "https://jmoney.dev/cidr-encoder"
  version "0.1"
  license "Apache 2.0"
  depends_on :macos

  on_arm do
    url "https://github.com/jmoney/cidr-encoder/releases/download/v0.1/tokenizer_cli_0.1_darwin_arm64.tar.gz"
    sha256 "188e2dc2f9a7e9c637d468ad84d659a28d77f54960aa6400a6144f76ce00a683"

    def install
      bin.install "cidr-encoder"
    end
  end

  test do
    system "#{bin}/cidr-encoder -h"
  end
end
