# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EchoServer < Formula
  desc "Server that echos a request"
  homepage "https://jmoney.dev/echo-server"
  version "0.2"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmoney/echo-server/releases/download/v0.2/echo-server_0.2_darwin_arm64.tar.gz"
      sha256 "083a82f560327f0b6ae338dab0c2f532876e5d2bd1f255a836fc3b2f7a41f37f"

      def install
        bin.install "echo-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/echo-server/releases/download/v0.2/echo-server_0.2_darwin_amd64.tar.gz"
      sha256 "f3a7d4e721752d07681227cb192333e43cef3acc1711dcf36f945bf2ec32a061"

      def install
        bin.install "echo-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmoney/echo-server/releases/download/v0.2/echo-server_0.2_linux_arm64.tar.gz"
      sha256 "2edf6ee77f94bcab5ee678d6a91925d4ca0803a91c8a757dbc40ed27f8d664e7"

      def install
        bin.install "echo-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/echo-server/releases/download/v0.2/echo-server_0.2_linux_amd64.tar.gz"
      sha256 "43aa9162b281217f9f92ab477561b36180bc54cc1d2eb8d1fb0447b620ef43d0"

      def install
        bin.install "echo-server"
      end
    end
  end

  test do
    system "#{bin}/echo-server -h"
  end
end
