# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ServerTlsMetrics < Formula
  desc "Reports tls certificate metrics"
  homepage "https://jmoney.dev/server-tls-metrics"
  version "0.3.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmoney/server-tls-metrics/releases/download/0.3.1/server-tls-metrics_0.3.1_Darwin_arm64.tar.gz"
      sha256 "1a0a33b260790d095bfef8f0e052f15cdd2ef71ae7ace80e60bada22e8a1ad05"

      def install
        bin.install "server-tls-metrics"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/server-tls-metrics/releases/download/0.3.1/server-tls-metrics_0.3.1_Darwin_x86_64.tar.gz"
      sha256 "53bdb0f439b6ddea3aca67fe83e9b7c08270469afdaf0acb77519ee4636a645a"

      def install
        bin.install "server-tls-metrics"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmoney/server-tls-metrics/releases/download/0.3.1/server-tls-metrics_0.3.1_Linux_arm64.tar.gz"
      sha256 "11ef29d304882e99996fb2fe47fa9f2e530ea95083322ed87a8dd2fc173dded0"

      def install
        bin.install "server-tls-metrics"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/server-tls-metrics/releases/download/0.3.1/server-tls-metrics_0.3.1_Linux_x86_64.tar.gz"
      sha256 "999301d519664ea26369d52cb48edb25c3b24bf8d97399466cb405931da53707"

      def install
        bin.install "server-tls-metrics"
      end
    end
  end

  test do
    system "#{bin}/server-tls-metrics -h"
  end
end
