# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ServerTlsMonitor < Formula
  desc "Reports tls certificate metrics"
  homepage "https://jmoney.dev/server-tls-monitor"
  version "0.1.11"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmoney/server-tls-monitor/releases/download/v0.1.11/server-tls-monitor_0.1.11_Darwin_arm64.tar.gz"
      sha256 "a31531255d23668d4d15f7871e950bc38fe53fe056ee47f79b195ba271d95d91"

      def install
        bin.install "server-tls-monitor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/server-tls-monitor/releases/download/v0.1.11/server-tls-monitor_0.1.11_Darwin_x86_64.tar.gz"
      sha256 "5b1e382d324db82d2537b4798194efabc32cc9290394daada2a203e4a2c38221"

      def install
        bin.install "server-tls-monitor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmoney/server-tls-monitor/releases/download/v0.1.11/server-tls-monitor_0.1.11_Linux_arm64.tar.gz"
      sha256 "f59e47e06da09b4dcb572c7edc4a6cb05f130464816264656b3df05faf0eb3c2"

      def install
        bin.install "server-tls-monitor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/server-tls-monitor/releases/download/v0.1.11/server-tls-monitor_0.1.11_Linux_x86_64.tar.gz"
      sha256 "960531db62967e2cf7c43ba4dce198e5e62302c0470355c342e1499755be256b"

      def install
        bin.install "server-tls-monitor"
      end
    end
  end

  test do
    system "#{bin}/server-tls-monitor -h"
  end
end
