# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ServerTlsMonitor < Formula
  desc "Reports tls certificate metrics"
  homepage "https://jmoney.dev/"
  version "0.1.7"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmoney/server-tls-monitor/releases/download/v0.1.7/server-tls-monitor_0.1.7_Darwin_arm64.tar.gz"
      sha256 "2b32640d9d3b4a06b11a9aea959b3b61630e29212fd03a3be284df1a44123cca"

      def install
        bin.install "server-tls-monitor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/server-tls-monitor/releases/download/v0.1.7/server-tls-monitor_0.1.7_Darwin_x86_64.tar.gz"
      sha256 "088d7e95035f6a287e13b8a06fa5fb996e0af3b7d739dc3f47417f0306850bc3"

      def install
        bin.install "server-tls-monitor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmoney/server-tls-monitor/releases/download/v0.1.7/server-tls-monitor_0.1.7_Linux_arm64.tar.gz"
      sha256 "1c322daa7d49e5540a18241bd8ffd40f5a978c94f20ca1f543b02ffc7ec0bbe1"

      def install
        bin.install "server-tls-monitor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/server-tls-monitor/releases/download/v0.1.7/server-tls-monitor_0.1.7_Linux_x86_64.tar.gz"
      sha256 "0a2acbb0be76cd7c4eb403ad57c0f05cd85b79ee815c4dbaebccfa05aaf9fa34"

      def install
        bin.install "server-tls-monitor"
      end
    end
  end

  test do
    system "#{bin}/server-tls-monitor -h"
  end
end
