# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ServerTlsMetricsAT021 < Formula
  desc "Reports tls certificate metrics"
  homepage "https://jmoney.dev/server-tls-monitor"
  version "0.2.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/server-tls-metrics/releases/download/0.2.1/server-tls-metrics_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "f3c2dabd00a790d0a313ec088ab9483aef9d6ec2f0a984d7e2e5b2159dc6acc9"

      def install
        bin.install "server-tls-monitor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmoney/server-tls-metrics/releases/download/0.2.1/server-tls-metrics_0.2.1_Darwin_arm64.tar.gz"
      sha256 "7f83e21ae50f288f98a8c8a96af4518d2e0c8123875b853df21b8ee0fee5f95e"

      def install
        bin.install "server-tls-monitor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmoney/server-tls-metrics/releases/download/0.2.1/server-tls-metrics_0.2.1_Linux_arm64.tar.gz"
      sha256 "7246d835550fb199f28ecb63d48b281bb24fdc47d546e8c4c092bc829832bb3e"

      def install
        bin.install "server-tls-monitor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/server-tls-metrics/releases/download/0.2.1/server-tls-metrics_0.2.1_Linux_x86_64.tar.gz"
      sha256 "5c4da072db3b1440ab60e01e6a6506c7f2bf20e8ccd509a35351fb3586fec894"

      def install
        bin.install "server-tls-monitor"
      end
    end
  end

  test do
    system "#{bin}/server-tls-monitor -h"
  end
end
