# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class X509MetricsAT100 < Formula
  desc "Reports tls certificate metrics"
  homepage "https://jmoney.dev/x509-metrics"
  version "1.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmoney/x509-metrics/releases/download/1.0.0/x509-metrics_1.0.0_darwin_arm64.tar.gz"
      sha256 "5b0a23dc597fb035f69e40306fc20333de6d025bd77b7eba03e3f2781d3a4fdd"

      def install
        bin.install "x509-metrics"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/x509-metrics/releases/download/1.0.0/x509-metrics_1.0.0_darwin_x86_64.tar.gz"
      sha256 "d3c0e0283798bb454fdd703d7d0603f8b3e2e5982617803be428a3425adca268"

      def install
        bin.install "x509-metrics"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmoney/x509-metrics/releases/download/1.0.0/x509-metrics_1.0.0_linux_arm64.tar.gz"
      sha256 "ca03844968cffc9793ee3182c359670503ceba6c0dfddf6e07de9a870ed37605"

      def install
        bin.install "x509-metrics"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmoney/x509-metrics/releases/download/1.0.0/x509-metrics_1.0.0_linux_x86_64.tar.gz"
      sha256 "c82902d3592af05e0572133b3c75b57babb6d901ccf46d7d34d86f788040f948"

      def install
        bin.install "x509-metrics"
      end
    end
  end

  test do
    system "#{bin}/x509-metrics -h"
  end
end
